from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, companies, dashboard, health, redis, environment_variables, tenant, audit_log, tokens, roles, departments, two_factor, devices, logging_history, sessions, api_keys, password_policy, account_lock, security_dashboard

api_router = APIRouter()
api_router.include_router(health.router, prefix="", tags=["Health"])
api_router.include_router(auth.router, prefix="/auth", tags=["Auth"])
api_router.include_router(users.router, prefix="/users", tags=["Users"])
api_router.include_router(companies.router, prefix="/companies", tags=["Companies"])
api_router.include_router(departments.router, prefix="/departments", tags=["Departments"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["Dashboard"])
api_router.include_router(redis.router, prefix="/redis", tags=["Redis"])
api_router.include_router(environment_variables.router, prefix="/environment-variables", tags=["Environment Variables"])
api_router.include_router(tenant.router, prefix="/tenants", tags=["Tenants"])
api_router.include_router(audit_log.router, prefix="/audit-logs", tags=["Audit Logs"])
api_router.include_router(tokens.router, prefix="/tokens", tags=["Tokens"])
api_router.include_router(roles.router, prefix="/roles", tags=["RBAC"])
api_router.include_router(two_factor.router, prefix="/auth", tags=["Auth"])
api_router.include_router(devices.router, prefix="/devices", tags=["Devices"])
api_router.include_router(logging_history.router, prefix="/logging", tags=["Logging History"])
api_router.include_router(sessions.router, prefix="/sessions", tags=["Sessions"])
api_router.include_router(api_keys.router, prefix="/api-keys", tags=["API Keys"])
api_router.include_router(password_policy.router, prefix="/password-policy", tags=["Password Policy"])
api_router.include_router(account_lock.router, prefix="/account-lock", tags=["Account Lock"])
api_router.include_router(security_dashboard.router, prefix="/security", tags=["Security Dashboard"])
