"""create_logging_configuration

Rrevision = '0023'
down_revision = '0022'
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: Union[str, None] = '0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'logging_configurations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('log_level', sa.String(length=20), nullable=False),
        sa.Column('enable_database_logging', sa.Boolean(), nullable=False),
        sa.Column('enable_console_logging', sa.Boolean(), nullable=False),
        sa.Column('log_format', sa.String(length=50), nullable=False),
        sa.Column('retention_days', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logging_configurations_company_id'), 'logging_configurations', ['company_id'], unique=True)
    op.create_index(op.f('ix_logging_configurations_id'), 'logging_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logging_configurations_id'), table_name='logging_configurations')
    op.drop_index(op.f('ix_logging_configurations_company_id'), table_name='logging_configurations')
    op.drop_table('logging_configurations')
    # ### end Alembic commands ###
